[project]
name = "deepagentslangchain"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "deepagents>=0.7.14",
    "dotenv>=0.9.9",
    "langchain[mcp]>=1.4.0",
    "langchain-openai>=1.6.2",
    "fastmcp>=4.0.5",
    "python-dotenv>=1.2.3",
    "modal>=1.5.5",
    "langchain-modal>=0.0.6",
    "langchain-quickjs",
]
